import React from 'react';
import {
  Search,
  Bell,
  Settings,
  LogOut,
  LogIn,
  LayoutDashboard,
  Home,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Plus,
  Pencil,
  Trash2,
  Save,
  XCircle,
  Check,
  CheckCircle,
  RefreshCw,
  MoreVertical,
  MoreHorizontal,
  FileText,
  Folder,
  FolderOpen,
  Image,
  Camera,
  Video,
  Mic,
  UploadCloud,
  Download,
  List,
  ListOrdered,
  Receipt,
  FileSpreadsheet,
  Phone,
  Mail,
  MessageSquare,
  Send,
  User,
  UserPlus,
  Users,
  Building,
  Heart,
  Star,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Flag,
  Share2,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Clock,
  Timer,
  Calendar,
  CalendarDays,
  Sun,
  Moon,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Tv,
  Headphones,
  Volume2,
  BarChart3,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  Briefcase,
  Store,
  ShoppingCart,
  CreditCard,
  Landmark,
  Wallet,
  Banknote,
  Tag,
  Percent,
  Play,
  Pause,
  Square,
  SkipForward,
  SkipBack,
  VolumeX,
  Volume1,
  MapPin,
  Map,
  Code,
  Terminal,
  Bug,
  Wrench,
  Zap,
  Sparkles,
  Bot,
  Trophy,
  Lightbulb,
  Brain,
  GraduationCap,
  BookOpen,
  Newspaper,
  Rss,
  Package,
  Handshake,
  Megaphone,
  Layers,
  Filter,
  DollarSign,
  LayoutGrid,
  Edit3,
  Copy,
  ExternalLink,
  Link,
  Paperclip,
  AtSign,
  Hash,
  Target,
  Compass,
  Navigation,
  Globe,
  Languages,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Quote,
  Code2,
  ListChecks,
  GripVertical,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Move,
  RotateCcw,
  Undo,
  Redo,
  Scissors,
  Clipboard,
  ClipboardCopy,
  ClipboardList,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Archive,
  Inbox,
  MailOpen,
  Reply,
  Forward,
  ReplyAll,
  UserCircle,
  UserCog,
  UserMinus,
  UserX,
  Building2,
  Factory,
  Warehouse,
  Wifi,
  WifiOff,
  Battery,
  BatteryFull,
  BatteryLow,
  BatteryCharging,
  BatteryWarning,
  Plug,
  Cable,
  HardDrive,
  Database,
  Server,
  Cloud,
  CloudOff,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  Fingerprint,
  Key,
  Scan,
  QrCode,
  Barcode,
  Plane,
  Train,
  Bus,
  Car,
  Truck,
  Anchor,
  Bike,
  Accessibility,
  Keyboard,
  MousePointer2,
  Mouse,
  Cast,
  Airplay,
  Radio,
  Music,
  Film,
  Clapperboard,
  Ticket,
  PiggyBank,
  Coins,
  Calculator,
  Activity,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Scale,
  Ruler,
  Gauge,
  AlarmClock,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarClock,
  CalendarRange,
  Hourglass,
  History,
  Network,
  Signal,
  SignalHigh,
  SignalMedium,
  SignalLow,
  Power,
  PowerOff,
  Sunrise,
  Sunset,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  Snowflake,
  Flame,
  Tornado,
  Trees,
  Recycle,
  Eraser,
  Paintbrush,
  PaintBucket,
  Palette,
  PenTool,
  Crop,
  FlipHorizontal,
  FlipVertical,
  RotateCw,
  Smile,
  Frown,
  Meh,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  ChevronLeft,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  ZoomIn,
  ZoomOut,
  Expand,
  Grid3X3,
  LayoutList,
  Rows3,
  Columns3,
  Grip,
  MoveVertical,
  MoveHorizontal,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  PlusCircle,
  Minus,
  MinusCircle,
  CheckSquare,
  HelpCircleIcon,
  InfoIcon,
  AlertTriangleIcon,
  AlertCircleIcon,
  StarIcon,
  HeartIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// 图标映射表 - Material Icons 名称映射到 Lucide Icons
const iconMapping: Record<string, LucideIcon> = {
  // 导航类
  'dashboard': LayoutDashboard,
  'home': Home,
  'menu': Menu,
  'search': Search,
  'notifications': Bell,
  'settings': Settings,
  'logout': LogOut,
  'login': LogIn,
  'arrow_back': ArrowLeft,
  'arrow_forward': ArrowRight,
  'arrow_upward': ArrowUp,
  'arrow_downward': ArrowDown,
  'chevron_right': ChevronRight,
  'chevron_left': ChevronLeft,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'close': X,
  
  // 操作类
  'add': Plus,
  'add_box': Plus,
  'add_circle': PlusCircle,
  'edit': Pencil,
  'delete': Trash2,
  'save': Save,
  'cancel': XCircle,
  'check': Check,
  'check_circle': CheckCircle,
  'refresh': RefreshCw,
  'more_vert': MoreVertical,
  'more_horiz': MoreHorizontal,
  
  // 文件类
  'description': FileText,
  'folder': Folder,
  'folder_open': FolderOpen,
  'image': Image,
  'photo': Image,
  'photo_camera': Camera,
  'camera_alt': Camera,
  'videocam': Video,
  'mic': Mic,
  'cloud_upload': UploadCloud,
  'cloud_download': Download,
  'download': Download,
  'view_list': List,
  'format_list_bulleted': List,
  'receipt': Receipt,
  'receipt_long': Receipt,
  'inventory': Package,
  'inventory_2': Package,
  
  // 通讯类
  'phone': Phone,
  'email': Mail,
  'chat': MessageSquare,
  'chat_bubble': MessageSquare,
  'chat_bubble_outline': MessageSquare,
  'send': Send,
  'message': MessageSquare,
  'forum': MessageSquare,
  
  // 用户类
  'person': User,
  'person_add': UserPlus,
  'people': Users,
  'group': Users,
  'groups': Users,
  'account_circle': UserCircle,
  'business': Building,
  'business_center': Briefcase,
  
  // 内容类
  'favorite': Heart,
  'favorite_border': Heart,
  'star': Star,
  'star_border': Star,
  'star_half': Star,
  'thumb_up': ThumbsUp,
  'thumb_down': ThumbsDown,
  'bookmark': Bookmark,
  'flag': Flag,
  'share': Share2,
  
  // 状态类
  'visibility': Eye,
  'visibility_off': EyeOff,
  'lock': Lock,
  'lock_open': Unlock,
  'warning': AlertTriangle,
  'error': AlertCircle,
  'info': Info,
  'help': HelpCircle,
  'priority_high': AlertTriangle,
  
  // 时间类
  'schedule': Clock,
  'access_time': Clock,
  'timer': Timer,
  'date_range': Calendar,
  'event': Calendar,
  'calendar_today': CalendarDays,
  'today': CalendarDays,
  
  // 天气/主题类
  'wb_sunny': Sun,
  'nights_stay': Moon,
  'brightness_4': Moon,
  'brightness_7': Sun,
  'dark_mode': Moon,
  'light_mode': Sun,
  
  // 设备类
  'computer': Monitor,
  'desktop_mac': Monitor,
  'laptop': Laptop,
  'phone_iphone': Smartphone,
  'tablet': Tablet,
  'tv': Tv,
  'headset': Headphones,
  'speaker': Volume2,
  
  // 功能类
  'analytics': BarChart3,
  'assessment': BarChart3,
  'insights': LineChart,
  'trending_up': TrendingUp,
  'trending_down': TrendingDown,
  'bar_chart': BarChart3,
  'pie_chart': PieChart,
  'show_chart': LineChart,
  'data_usage': Activity,
  
  // 业务类
  'work': Briefcase,
  'store': Store,
  'storefront': Store,
  'shopping_cart': ShoppingCart,
  'payment': CreditCard,
  'credit_card': CreditCard,
  'account_balance': Landmark,
  'wallet': Wallet,
  'money': Banknote,
  'attach_money': DollarSign,
  'calculate': Calculator,
  'local_offer': Tag,
  'loyalty': Heart,
  
  // 媒体类
  'play_arrow': Play,
  'pause': Pause,
  'stop': Square,
  'skip_next': SkipForward,
  'skip_previous': SkipBack,
  'volume_up': Volume2,
  'volume_down': Volume1,
  'volume_off': VolumeX,
  'volume_mute': VolumeX,
  
  // 地图/位置类
  'place': MapPin,
  'location_on': MapPin,
  'map': Map,
  
  // 开发类
  'code': Code,
  'terminal': Terminal,
  'developer_mode': Code2,
  'bug_report': Bug,
  'build': Wrench,
  
  // 其他
  'flash_on': Zap,
  'flash_off': Zap,
  'bolt': Zap,
  'auto_fix_high': Sparkles,
  'auto_awesome': Sparkles,
  'smart_toy': Bot,
  'emoji_events': Trophy,
  'emoji_objects': Lightbulb,
  'lightbulb': Lightbulb,
  'psychology': Brain,
  'school': GraduationCap,
  'book': BookOpen,
  'library_books': BookOpen,
  'article': FileText,
  'newspaper': Newspaper,
  'feed': Rss,
  
  // 额外映射
  'handshake': Handshake,
  'campaign': Megaphone,
  'assignment': CheckCircle,
  'assignment_turned_in': CheckCircle,
  'layers': Layers,
  'list': List,
  'calendar_view_month': Calendar,
  'filter_list': Filter,
  'payments': CreditCard,
  'ad_units': LayoutGrid,
  'image_search': Search,
  'zoom_in': ZoomIn,
  'category': LayoutGrid,
  'post_add': FilePlus,
  
  // 额外常用图标
  'link': Link,
  'external_link': ExternalLink,
  'paperclip': Paperclip,
  'at_sign': AtSign,
  'hash': Hash,
  'target': Target,
  'compass': Compass,
  'navigation': Navigation,
  'globe': Globe,
  'languages': Languages,
  'type': Type,
  'format_align_left': AlignLeft,
  'format_align_center': AlignCenter,
  'format_align_right': AlignRight,
  'format_align_justify': AlignJustify,
  'format_bold': Bold,
  'format_italic': Italic,
  'format_underlined': Underline,
  'format_strikethrough': Strikethrough,
  'format_quote': Quote,
  'format_list_numbered': ListOrdered,
  'maximize': Maximize,
  'minimize': Minimize,
  'fullscreen': Maximize2,
  'exit_fullscreen': Minimize2,
  'move': Move,
  'rotate_left': RotateCcw,
  'undo': Undo,
  'redo': Redo,
  'cut': Scissors,
  'copy': Copy,
  'paste': Clipboard,
  'clipboard': Clipboard,
  'archive': Archive,
  'inbox': Inbox,
  'mail_open': MailOpen,
  'reply': Reply,
  'forward': Forward,
  'reply_all': ReplyAll,
  'user_cog': UserCog,
  'user_minus': UserMinus,
  'user_x': UserX,
  'building_2': Building2,
  'factory': Factory,
  'warehouse': Warehouse,
  'wifi': Wifi,
  'wifi_off': WifiOff,
  'battery_full': BatteryFull,
  'battery_alert': BatteryWarning,
  'plug': Plug,
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'shield': Shield,
  'shield_check': ShieldCheck,
  'shield_alert': ShieldAlert,
  'key': Key,
  'fingerprint': Fingerprint,
  'scan': Scan,
  'qr_code': QrCode,
  'barcode': Barcode,
  'plane': Plane,
  'train': Train,
  'bus': Bus,
  'car': Car,
  'truck': Truck,
  'anchor': Anchor,
  'bike': Bike,
  'accessibility': Accessibility,
  'keyboard': Keyboard,
  'mouse': Mouse,
  'cast': Cast,
  'airplay': Airplay,
  'radio': Radio,
  'music': Music,
  'film': Film,
  'clapperboard': Clapperboard,
  'ticket': Ticket,
  'piggy_bank': PiggyBank,
  'coins': Coins,
  'percent': Percent,
  'invoice': FileText,
  'chart_line': LineChart,
  'chart_bar': BarChart3,
  'chart_pie': PieChart,
  'activity': Activity,
  'heart_pulse': HeartPulse,
  'stethoscope': Stethoscope,
  'pill': Pill,
  'syringe': Syringe,
  'scale': Scale,
  'ruler': Ruler,
  'gauge': Gauge,
  'stopwatch': Timer,
  'alarm_clock': AlarmClock,
  'calendar_check': CalendarCheck,
  'calendar_x': CalendarX,
  'calendar_plus': CalendarPlus,
  'calendar_minus': CalendarMinus,
  'calendar_clock': CalendarClock,
  'calendar_range': CalendarRange,
  'hourglass': Hourglass,
  'history': History,
  'network': Network,
  'signal': Signal,
  'power': Power,
  'power_off': PowerOff,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'cloud_rain': CloudRain,
  'cloud_snow': CloudSnow,
  'cloud_lightning': CloudLightning,
  'wind': Wind,
  'thermometer': Thermometer,
  'droplets': Droplets,
  'umbrella': Umbrella,
  'snowflake': Snowflake,
  'flame': Flame,
  'tornado': Tornado,
  'trees': Trees,
  'recycle': Recycle,
  'eraser': Eraser,
  'paintbrush': Paintbrush,
  'paint_bucket': PaintBucket,
  'palette_icon': Palette,
  'pen_tool': PenTool,
  'crop': Crop,
  'flip_horizontal': FlipHorizontal,
  'flip_vertical': FlipVertical,
  'rotate_right': RotateCw,
  'smile': Smile,
  'frown': Frown,
  'meh': Meh,
  'support_agent': Bot,
  'perm_media': Image,
  'engineering': Wrench,

  // 新增菜单图标
  'apartment': Building,
  'gate': Building,
  'grid_view': LayoutGrid,
  'directions_car': Car,
  'view_module': LayoutGrid,
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  size?: number;
  className?: string;
}

export const Icon: React.FC<IconProps> = ({ name, size = 24, className = '', ...props }) => {
  const LucideIconComponent = iconMapping[name];
  
  if (!LucideIconComponent) {
    console.warn(`Icon "${name}" not found, using fallback`);
    return <HelpCircle size={size} className={className} {...props} />;
  }
  
  return (
    <LucideIconComponent 
      size={size} 
      className={className}
      {...props}
    />
  );
};

export default Icon;
